# Generated by Django 3.1.6 on 2021-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='UpcomingProperty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
    ]
