# Generated by Django 3.1.6 on 2021-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='OneBHK',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
