# Generated by Django 3.1.6 on 2021-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0002_propertylist_onebhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='FourBHK',
            field=models.TextField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='ThreeBHK',
            field=models.TextField(default=' ', max_length=90),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='TwoBHK',
            field=models.TextField(default=' ', max_length=99),
        ),
    ]
