# Generated by Django 3.1.6 on 2021-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0003_auto_20210322_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpropertylist',
            name='ExFourBHK',
            field=models.TextField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='ExOneBHK',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='ExThreeBHK',
            field=models.TextField(default=' ', max_length=90),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='ExTwoBHK',
            field=models.TextField(default=' ', max_length=99),
        ),
    ]
