# Generated by Django 3.1.6 on 2021-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0005_auto_20210322_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylist',
            name='FourBHK',
        ),
        migrations.RemoveField(
            model_name='propertylist',
            name='OneBHK',
        ),
        migrations.RemoveField(
            model_name='propertylist',
            name='ThreeBHK',
        ),
        migrations.RemoveField(
            model_name='propertylist',
            name='TwoBHK',
        ),
        migrations.AddField(
            model_name='propertylist',
            name='ExFourBHK',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='ExOneBHK',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='ExThreeBHK',
            field=models.CharField(default=' ', max_length=90),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='ExTwoBHK',
            field=models.CharField(default=' ', max_length=99),
        ),
    ]
