# Generated by Django 3.1.6 on 2021-03-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0016_auto_20210312_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='Icon',
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Property_Image',
            field=models.ImageField(upload_to='SHIApp/static/HotProperty_images'),
        ),
    ]
