# Generated by Django 3.1.6 on 2021-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0017_auto_20210320_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Property_Image',
            field=models.ImageField(upload_to='SHIProj/SHIApp/static/HotProperty_images'),
        ),
    ]
