# Generated by Django 3.1.6 on 2021-03-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0019_auto_20210320_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='Logo',
            field=models.FileField(upload_to='media/BuilderLogo'),
        ),
        migrations.AlterField(
            model_name='hotpropertyimages',
            name='Images',
            field=models.ImageField(upload_to='media/HotIndividualPropImgs'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Floor_Plan_1BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Hot_Prop_Floor_Plan_1BHK'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Floor_Plan_2BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Hot_Prop_Floor_Plan_2BHK'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Floor_Plan_3BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Hot_Prop_Floor_Plan_3BHK'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Floor_Plan_4BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Hot_Prop_Floor_Plan_4BHK'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Master_Plan',
            field=models.ImageField(blank=True, default='', upload_to='media/HotMaster_Plans'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Property_Image',
            field=models.ImageField(upload_to='media/HotProperty_images'),
        ),
        migrations.AlterField(
            model_name='hotpropertylist',
            name='Video',
            field=models.FileField(blank=True, default='', upload_to='media/HotPropVideos'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Images',
            field=models.ImageField(upload_to='media/IndividualPropImgs'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Floor_Plan_1BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Floor_Plan_1BHK'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Floor_Plan_2BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Floor_Plan_2BHK'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Floor_Plan_3BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Floor_Plan_3BHK'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Floor_Plan_4BHK',
            field=models.ImageField(blank=True, default='', upload_to='media/Floor_Plan_4BHK'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Master_Plan',
            field=models.ImageField(blank=True, default='', upload_to='media/Master_Plans'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Property_Image',
            field=models.ImageField(upload_to='media/Property_images'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Video',
            field=models.FileField(blank=True, default='', upload_to='media/Videos'),
        ),
    ]
