# Generated by Django 3.1.6 on 2021-03-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0021_auto_20210322_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotpropertylist',
            old_name='Prop_BHK1Price',
            new_name='BHK1Price',
        ),
        migrations.RenameField(
            model_name='hotpropertylist',
            old_name='Prop_BHK2Price',
            new_name='BHK2Price',
        ),
        migrations.RenameField(
            model_name='hotpropertylist',
            old_name='Prop_BHK3Price',
            new_name='BHK3Price',
        ),
        migrations.RenameField(
            model_name='hotpropertylist',
            old_name='Prop_BHK4Price',
            new_name='BHK4Price',
        ),
    ]
